services:

  db:
    image: postgres:16
    container_name: weather_db
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: ./app/
    container_name: weather_web
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx
    container_name: weather_nginx
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  db_data:
